version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run tslint
  
  deploy:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: docker build -t hyunsub/api:latest .
      - run: docker save -o hyunsub-api.tar hyunsub/api:latest
      - add_ssh_keys:
          fingerprints:
            - "7b:42:e7:9f:87:83:6f:ad:58:ba:4d:cc:82:4a:75:5c"
      - run: rsync -ah -e "ssh -o StrictHostKeyChecking=no" hyunsub-api.tar hyunsub@home.hyunsub.kim:/home/hyunsub/docker/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master