name: Main

on:
  push:
    branches:
    - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
    - run: npm install
    - run: npm run tslint
    - run: npm run check
    - run: docker build -t hyunsub/api .
    - run: docker save -o hyunsub-api.tar hyunsub/api
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "hyunsub-api.tar"
        target: "/home/hyunsub/hyunsub/"
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd ~/hyunsub; docker load -i hyunsub-api.tar; docker-compose up -d --force-recreate api